[WIP][11.0][ADD] cb_resource_calendar_clone_monday
tegin/cb-addons pull request #250
Opened 2019-08-22 14:40 UTC by jarroyomorales

La idea de este modulo es que a la hora de definir un calendario, el usuario introduzca el horario de lunes y al darle a un boton propagar lunes o algo así, te copie lo que hayas puesto en lunes para el resto de la semana.

Está totalmente WIP, el nombre seguramente deberia ser otro, quizas se tendria que hacer con un wizard, no sé, pero la idea es esa. No tener que introducir 5 veces lo mismo.

2019-09-02 14:28 UTC, etobella commented
Change module name for cb_resource_calendar_propagate_monday

2019-09-02 14:28 UTC, etobella approved these changes

2019-09-02 14:32 UTC, etobella requested changes

2019-09-02 14:32 UTC, etobella commented on cb_resource_calendar_clone_monday/views/resource_calendar.xml
> +            <field name="name" position="attributes">
Maybe better to autofill it

2019-09-02 14:32 UTC, etobella commented on cb_resource_calendar_clone_monday/models/resource_calendar.py
> +                    values = attendance.copy_data({'dayofweek': str(i)})
add `'name': 'Day of week ' + attendance.name` or `'name': 'Day of week' + 'attendance.start + end`

2019-09-02 14:32 UTC, etobella commented on cb_resource_calendar_clone_monday/views/resource_calendar.xml
> +            <field name="name" position="attributes">
Not invisible...

2019-09-03 07:00 UTC, jarroyomorales commented
@etobella Lo del nombre sigue sin convencerme. Queda muy raro para el usuario, el tener que poner un nombre din decir el dia de la semana, Nose, además no veo que aporte ninguna información.

2019-09-11 05:48 UTC, etobella approved these changes

2019-09-11 05:48 UTC, merged