[11.0][FIX] Add group to tags and other fixes
tegin/cb-addons pull request #254
Opened 2019-08-28 14:45 UTC by jarroyomorales

2019-09-02 14:25 UTC, etobella requested changes

2019-09-02 14:25 UTC, etobella commented on cb_holidays_compute_mix/views/hr_module_views.xml
> +        <field name="groups_id" eval="[(6, 0, [ref('make_invisible')])]"/>
"active" eval="False"

2019-09-03 06:42 UTC, jarroyomorales commented on cb_holidays_compute_mix/views/hr_module_views.xml
> +        <field name="groups_id" eval="[(6, 0, [ref('make_invisible')])]"/>
Fixeeeed

2019-09-04 14:03 UTC, jarroyomorales commented
@etobella This is ready to merge

2019-09-10 14:50 UTC, etobella approved these changes

2019-09-11 05:46 UTC, merged