[11.0][FIX] Deleting unnecessary info HR
tegin/cb-addons pull request #266
Opened 2019-09-27 10:03 UTC by jarroyomorales

Pues eso

2019-09-27 10:08 UTC, jarroyomorales commented
Hablar sobre bank account antes de mergear

2019-10-14 08:14 UTC, etobella requested changes

2019-10-14 08:14 UTC, etobella commented on cb_hr_views/models/hr_attendance.py
> +        string='Center',
readonly=True, store=True

2019-10-14 08:14 UTC, etobella commented on cb_hr_views/views/hr_attendance_module_views.xml
> +                <field name="center_id"/>
Probably will not work if not stored...

2019-10-15 09:32 UTC, jarroyomorales commented
@etobella This is RTM

2019-10-15 10:27 UTC, etobella approved these changes

2019-10-15 10:27 UTC, merged